"""add images columns for yuque screenshots

Revision ID: 108c3b17f470
Revises: be8621870f54
Create Date: 2026-08-17 16:11:56.389123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # Vector 列类型，autogenerate 生成的迁移需要它
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '108c3b17f470'
down_revision: Union[str, Sequence[str], None] = 'be8621870f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'images')
    op.drop_column('chunks', 'images')
    # ### end Alembic commands ###
