"""add verified_answers for answer-level corrections

Revision ID: 1d87ea882e36
Revises: 3420931c06cb
Create Date: 2026-08-20 10:53:30.940073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # Vector 列类型，autogenerate 生成的迁移需要它


# revision identifiers, used by Alembic.
revision: str = '1d87ea882e36'
down_revision: Union[str, Sequence[str], None] = '3420931c06cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verified_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.String(length=1024), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verified_answers_author_id'), 'verified_answers', ['author_id'], unique=False)
    op.create_index(op.f('ix_verified_answers_question'), 'verified_answers', ['question'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verified_answers_question'), table_name='verified_answers')
    op.drop_index(op.f('ix_verified_answers_author_id'), table_name='verified_answers')
    op.drop_table('verified_answers')
    # ### end Alembic commands ###
