"""mark chunks that come from a verified answer

Revision ID: 253da29f3f99
Revises: 1d87ea882e36
Create Date: 2026-08-20 10:54:49.998254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # Vector 列类型，autogenerate 生成的迁移需要它


# revision identifiers, used by Alembic.
revision: str = '253da29f3f99'
down_revision: Union[str, Sequence[str], None] = '1d87ea882e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'verified')
    # ### end Alembic commands ###
