"""add agent state columns to conversations

Revision ID: 58e813bb7a44
Revises: 333a562a55eb
Create Date: 2026-08-17 23:56:16.945469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # Vector 列类型，autogenerate 生成的迁移需要它
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58e813bb7a44'
down_revision: Union[str, Sequence[str], None] = '333a562a55eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('profile', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    op.add_column('conversations', sa.Column('checklist', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    op.add_column('conversations', sa.Column('export_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'export_path')
    op.drop_column('conversations', 'checklist')
    op.drop_column('conversations', 'profile')
    # ### end Alembic commands ###
