"""add corrections table for web-authored kb fixes

Revision ID: 597da02c59d4
Revises: 58e813bb7a44
Create Date: 2026-08-18 18:07:26.941964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # Vector 列类型，autogenerate 生成的迁移需要它


# revision identifiers, used by Alembic.
revision: str = '597da02c59d4'
down_revision: Union[str, Sequence[str], None] = '58e813bb7a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('based_on', sa.String(length=64), nullable=False),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrections_author_id'), 'corrections', ['author_id'], unique=False)
    op.create_index(op.f('ix_corrections_target_url'), 'corrections', ['target_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corrections_target_url'), table_name='corrections')
    op.drop_index(op.f('ix_corrections_author_id'), table_name='corrections')
    op.drop_table('corrections')
    # ### end Alembic commands ###
