"""add request_trace for per-request observability and feedback

Revision ID: 96f8bd847be6
Revises: 253da29f3f99
Create Date: 2026-08-20 16:44:34.608026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # Vector 列类型，autogenerate 生成的迁移需要它
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96f8bd847be6'
down_revision: Union[str, Sequence[str], None] = '253da29f3f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_trace',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('route', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('tools', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=True),
    sa.Column('private_hits', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('ttfb_ms', sa.Integer(), nullable=True),
    sa.Column('total_ms', sa.Integer(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('answer_chars', sa.Integer(), nullable=False),
    sa.Column('no_answer', sa.Boolean(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('feedback', sa.String(length=8), nullable=True),
    sa.Column('feedback_reason', sa.String(length=24), nullable=True),
    sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_trace_created_at'), 'request_trace', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_trace_feedback'), 'request_trace', ['feedback'], unique=False)
    op.create_index('ix_request_trace_feedback_recent', 'request_trace', ['created_at'], unique=False, postgresql_where=sa.text('feedback IS NOT NULL'))
    op.create_index(op.f('ix_request_trace_request_id'), 'request_trace', ['request_id'], unique=False)
    op.create_index(op.f('ix_request_trace_route'), 'request_trace', ['route'], unique=False)
    op.create_index(op.f('ix_request_trace_user_id'), 'request_trace', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_trace_user_id'), table_name='request_trace')
    op.drop_index(op.f('ix_request_trace_route'), table_name='request_trace')
    op.drop_index(op.f('ix_request_trace_request_id'), table_name='request_trace')
    op.drop_index('ix_request_trace_feedback_recent', table_name='request_trace', postgresql_where=sa.text('feedback IS NOT NULL'))
    op.drop_index(op.f('ix_request_trace_feedback'), table_name='request_trace')
    op.drop_index(op.f('ix_request_trace_created_at'), table_name='request_trace')
    op.drop_table('request_trace')
    # ### end Alembic commands ###
